import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
// eslint-disable-next-line import/order
import { ChartColumnBigIcon } from 'lucide-react';
// eslint-disable-next-line import/order
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton } from '@clerk/nextjs' ;

import UserDropdown from '@/app/user-dropdown';
import { Button } from '@/components/ui/button';
import { Toaster } from '@/components/ui/sonner';

const poppins = Poppins({
    variable: '--font-poppins',
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body
                className={`${poppins.variable} antialiased`}
            >
            <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between ">
                <Link href={'/'} className={'font-bold text-2xl flex gap-1 items-center '}>
                    <ChartColumnBigIcon className={'text-lime-500'}/> Finance Tracker
                </Link>
                <SignedOut>
                    <div className={'flex items-center'}>
                        <Button asChild variant={'link'} className={'text-white'}>
                            <SignInButton/>
                        </Button>
                        <Button asChild variant={'link'} className={'text-white'}>
                            <SignUpButton/>
                        </Button>
                    </div>
                </SignedOut>
                <SignedIn>
                    <UserDropdown/>
                </SignedIn>
            </nav>
            {children}
            <Toaster/>
            </body>
            </html>
        </ClerkProvider>
    );
}
