import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {ChartColumnBigIcon} from "lucide-react";
import {ClerkProvider, SignedOut, SignInButton, SignUpButton} from "@clerk/nextjs";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body
                className={`${poppins.variable} antialiased`}
            >
            <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between ">
                <Link href={'/'} className={'font-bold text-2xl flex gap-1 items-center '}>
                    <ChartColumnBigIcon className={'text-lime-500'}/> NextCash
                </Link>
                <SignedOut>
                    <div className={'flex items-center'}>
                        <SignInButton/>
                        <SignUpButton/>
                    </div>
                </SignedOut>
            </nav>
            {children}
            </body>
            </html>
        </ClerkProvider>
    );
}
